////
 Copyright (c) 2024 CEA LIST, Artal Technologies.
 This program and the accompanying materials
 are made available under the terms of the Eclipse Public License v2.0
 which accompanies this distribution, and is available at
 https://www.eclipse.org/legal/epl-2.0/

 SPDX-License-Identifier: EPL-2.0

 Contributors:
     Obeo - Initial API and implementation 
     Aurelien Didier (Artal Technologies) - Issue 201
     Marcos Didonet Del Fabro (CEA LIST) 
////
= IoMT Modeling Tool Documentation
IoMT Modeling Tool v{papyrus-web-version} - {git-commit-id-abbrev}

The IoMT Modeling Tool (IoMT) is an open-source web-based modeling tool, specialized in the design of Internet of Medical Things (IoMT) architectures. It is built on top of Papyrus Web, an Eclipse Foundation project that provides a web-based modeling environment.

- xref:iomt_howto/iomt_howto.adoc[HowTo - IoMT model creation]
- xref:iomt_howto/tvra_howto.adoc[HowTo - TVRA model instantiation]
- xref:iomt_howto/cwe_howto.adoc[HowTo - IoMT with constraints model instantiation]
- IoMT Profiles description
* xref:iomt_howto/iomt_architecture_profile.adoc[IoMT Profile]
* xref:iomt_howto/iomt_component_categories.adoc[IoMT Component Categories Profile]
* xref:iomt_howto/iomt_assets.adoc[IoMT Assets Profile]
* xref:iomt_howto/iomt_tvra.adoc[IoMT TVRA Profile]
- xref:features/import_export.adoc[Import/Export features]
- xref:codegen/papyrusweb_howto/gencode_howto.adoc[HowTo - PapyrusWeb CodeGeneration]
- xref:codegen/description_software_designer/sw_designer.adoc[Papyrus Software Designer for code generation]
- xref:features/ocl_querying.adoc[Persisted Element Specific Constraints]
- xref:user/userdoc.adoc[User documentation]
- xref:dev/dev-doc-index.adoc[Developper documentation]
- xref:spec/diagrams-spec-index.adoc[Detailed Diagram specification]
