<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
		<groupId>papyrus-web</groupId>
		<artifactId>papyrus-web-parent</artifactId>
		<version>2024.10.0</version>
		<relativePath>../papyrus-web-parent</relativePath>
	</parent>
  <artifactId>papyrus-web-iomt-assertions-profile</artifactId>
  <name>papyrus-web-iomt-assertions-profile</name>
  <description>Papyrus Web IOmT Assertions profile</description>
  
  	<dependencies>
		<!-- Internal dependencies -->
		<dependency>
			<groupId>papyrus-web</groupId>
			<artifactId>papyrus-web-application</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>papyrus-web</groupId>
			<artifactId>papyrus-web-representation-builder</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>papyrus-web</groupId>
			<artifactId>papyrus-web-sirius-contributions</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>papyrus-web</groupId>
			<artifactId>
				papyrus-web-iomt-assertions-profile-model
			</artifactId>
			<version>${project.version}</version>
		</dependency>	

		<!-- External Dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.uml2.plugins</groupId>
			<artifactId>org.eclipse.uml2.uml</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.uml2.plugins</groupId>
			<artifactId>org.eclipse.uml2.uml.resources</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.uml2.plugins</groupId>
			<artifactId>org.eclipse.uml2.common</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.uml2.plugins</groupId>
			<artifactId>org.eclipse.uml2.types</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.eclipse.platform</groupId>
		    <artifactId>org.eclipse.core.databinding.observable</artifactId>
		    <version>1.13.0</version>
		</dependency>
	</dependencies>
</project>