#  Copyright (c) 2024 CEA LIST.
#  All rights reserved. This program and the accompanying materials
#  are the property of CEA LIST, their use is subject to specific
#  agreement with the CEA LIST.

image: docker:24.0.2   # Use Docker-in-Docker (DinD) image

services:
  - docker:24.0.2-dind  # Service for Docker daemon

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  ENVIRONMENT: "build"
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared
  GIT_SUBMODULE_STRATEGY: recursive
  HARBOR_REGISTRY_URL: 7xiyijjn.gra7.container-registry.ovh.net
  DEEPLAB_REGISTRY_PROJECT: deeplab/codegenrcp


stages:
  - build
  - deploy

before_script:
  - docker info  # Check that Docker is working

build_image:
  stage: build
  script:
    - docker build -t codegen_rcp -f dockerfiles/rcp/Dockerfile .

push_image:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker tag codegen_rcp:latest ${HARBOR_REGISTRY_URL}/${DEEPLAB_REGISTRY_PROJECT}/codegen_rcp:${{ env.SHORT_IMAGE_TAG }}
    - docker tag codegen_rcp:latest ${HARBOR_REGISTRY_URL}/${DEEPLAB_REGISTRY_PROJECT}/codegen_rcp:${{ env.IMAGE_TAG }}
    - docker push ${HARBOR_REGISTRY_URL}/${DEEPLAB_REGISTRY_PROJECT}/codegen_rcp:${{ env.SHORT_IMAGE_TAG }}
    - docker push ${HARBOR_REGISTRY_URL}/${DEEPLAB_REGISTRY_PROJECT}/codegen_rcp:${{ env.IMAGE_TAG }}

