source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               .classpath,\
               lib/angus-activation-2.0.0.jar,\
               lib/commons-codec-1.11.jar,\
               lib/commons-logging-1.2.jar,\
               lib/httpclient-4.5.14.jar,\
               lib/httpcore-4.4.16.jar,\
               lib/istack-commons-runtime-4.1.1.jar,\
               lib/jakarta.activation-api-2.1.0.jar,\
               lib/jakarta.xml.bind-api-4.0.0.jar,\
               lib/jaxb-core-4.0.2.jar,\
               lib/jaxb-runtime-4.0.2.jar,\
               lib/sardine-5.12.jar,\
               lib/slf4j-api-2.0.7.jar,\
               lib/slf4j-simple-2.0.7.jar,\
               lib/txw2-4.0.2.jar,\
               lib/papyrus-web-iomt-assertions-profile-model-2024.2.1.jar,\
               lib/papyrus-web-iomt-assets-profile-model-2024.2.1.jar,\
               lib/papyrus-web-iomt-componentcategories-profile-model-2024.2.1.jar,\
               lib/papyrus-web-iomt-profile-model-2024.2.1.jar,\
               ,\
               resources/

