
services:
  database:
    image: postgres:12
    env_file:
      - .env    
  papyrusweb:
    image: papyrus-web-iomt:2025.05.07.11
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        USERNAME: ${GITHUB_USERNAME}
        PASSWORD: ${GITHUB_AUTH_TOKEN}              
    ports:
      - "8080:8080"
    env_file:
      - .env    
    depends_on:
      - database
      - codegenrcp
      - generateiomtapp

  codegenrcp:
    build:
      context: ../services/modeling-services-rcp
      dockerfile: dockerfiles/rcp/Dockerfile
    image: codegenrcp:2025.04.28
    ports:
      - "8083:8083"
    env_file:
      - .env    

  generateiomtapp:
    build:
      context: ../medsecuranceappgen
      dockerfile: dockerfiles/Dockerfile
    image: generateiomtapp:2025.05.07.11
    command: 
    ports:
      - "9000:9000"
    environment:
      APPWEB_URL: http://papyrusweb:8080

