
services:
  database:
    image: postgres:12
    env_file:
      - .env    
  papyrusweb:
    image: papyrus-web-iomt:2025.05.21
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        USERNAME: ${GITHUB_USERNAME}
        PASSWORD: ${GITHUB_AUTH_TOKEN}              
    ports:
      - "8080:8080"
    env_file:
      - .env    
    depends_on:
      - database
      - codegenrcp
      - generateiomtapp
    volumes:
      - ../.git:/build/.git:ro
  codegenrcp:
    build:
      context: ../modeling-services-rcp
      dockerfile: dockerfiles/rcp/Dockerfile
    image: codegenrcp:2025.04.28
    ports:
      - "8083:8083"
    env_file:
      - .env    

  generateiomtapp:
    build:
      context: ../medsecuranceappgen
      dockerfile: dockerfiles/Dockerfile
      args:
        MAVEN_VERSION: 3.9.4
    image: iomtgen
    command: 
    ports:
      - "9000:9000"
    environment:
      APPWEB_URL: http://papyrusweb:8080

