spring.application.name=papyrus-web-generate-medsecurance-application

server.port=9000

#spring.mustache.suffix:.html

spring.datasource.url=jdbc:postgresql://localhost:5439/papyrus-web-db
spring.datasource.username=dbuser
spring.datasource.password=dbpwd
