#############################################################################
#  Copyright (c) 2025 CEA LIST.
#  
#  This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License 2.0
#  which accompanies this distribution, and is available at
#  https://www.eclipse.org/legal/epl-2.0/
# 
#  SPDX-License-Identifier: EPL-2.0
#  
#  Contributors:
#   Marcos Didonet Del Fabro (CEA LIST) - Initial implementation
#
#############################################################################

# Build instructions
# docker build --build-arg USERNAME=${GIT_USERNAME} PASSWORD=${GIT_AUTH_TOKEN} -t papyrusweb .
# Launch instructions. Note that it is necessary to have a running postgres image or local database
# docker run --name=papyrusweb-container -p 8080:8080 papyrusweb:latest

# Image for full compilation

FROM node:18.7 as papyrusweb-build

ADD . /build
WORKDIR /build/

ENV MAVEN_OPTS="-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
ENV MAVEN_VERSION="3.9.4"

ARG USERNAME
ARG PASSWORD

# Compile the frontend in one layer

RUN echo '//npm.pkg.github.com/:_authToken=${PASSWORD}' >> /build/frontend/.npmrc &&\
  cd frontend && npm install && npm ci && npm run build
RUN mkdir -p backend/papyrus-web-frontend/src/main/resources/static &&\
  cp -R frontend/papyrus-web/dist/* backend/papyrus-web-frontend/src/main/resources/static

# Uses an intermediate file to export the WEBAPP_VERSION
RUN export WEBAPP_VERSION=$(grep version frontend/package.json | awk -F \" '{print $4}') &&\
  echo $WEBAPP_VERSION > /build/WEBAPP_VERSION

# Update packages and compile the backend in another layer

RUN apt-get update &&\
  apt-get install openjdk-17-jdk -y &&\
  wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz &&\
  tar -xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz &&\
  export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH &&\
  mvn clean verify -DskipTests -Dcheckstyle.skip -f backend/pom.xml --settings settings.xml

COPY --from=papyrusweb-build /build/WEBAPP_VERSION /WEBAPP_VERSION
COPY --from=papyrusweb-build /build/backend/papyrus-web/target/ /.

# Image to run Papyrus Web

# FROM eclipse-temurin:17-jre as papyrusweb
FROM node:18.7 as papyrusweb

ARG WEBAPP_VERSION

RUN apt-get update && apt-get install -y openjdk-17-jre && apt-get clean cache
#### COPY --from=papyrusweb-build-back /build/backend/papyrus-web/target/papyrus-web-${WEBAPP_VERSION}.jar ./app.jar
COPY --from=papyrusweb-build /build/backend/papyrus-web/target/papyrus-web-${WEBAPP_VERSION}.jar ./app.jar
EXPOSE 8080

#RUN adduser --disabled-password myuser
#USER myuser

ENTRYPOINT ["java","-jar","/app.jar"]

#CMD [ "sh", "-c", "java -cp app.jar -Djava.security.egd=file:/dev/./urandom -Dloader.main=org.eclipse.papyrus.web.application.PapyrusApplication org.springframework.boot.loader.PropertiesLauncher" ]
#ENTRYPOINT java -Dpapyrus-web.graphql.websocket.allowed.origins="*" -jar ./app.jar --spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} --spring.datasource.username=${POSTGRES_USER} --spring.datasource.password=${POSTGRES_PASSWORD} --spring.liquibase.change-log=classpath:db/changelog/papyrus-web.db.changelog.xml 

