#Copyright (c) 2024 CEA LIST
#Secret to the image registry in a Harbor Open server, or any other
apiVersion: v1
data:
# Use a specific configuration for login into the service
  .dockerconfigjson: SOME ENCODED VALUE
kind: Secret
metadata:
  name: harbor-registry-pull-secret
  namespace: papyrusweb
type: kubernetes.io/dockerconfigjson
